"""添加用户和学生

Revision ID: d92bc82eadb5
Revises: 0001_initial
Create Date: 2026-03-13 18:12:47.633837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd92bc82eadb5'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False, comment='登录账号'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='展示姓名'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='student | teacher'),
    sa.Column('class_name', sa.String(length=100), nullable=True, comment='班级，仅学生有值'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('student_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=100), nullable=False, comment='与 StudentProgress.student_id 对齐'),
    sa.Column('unit_id', sa.BigInteger(), nullable=True, comment='统计所属单元，NULL 表示全局汇总'),
    sa.Column('total_submit_count', sa.Integer(), nullable=False, comment='总提交次数'),
    sa.Column('avg_ai_score', sa.Float(), nullable=True, comment='AI 平均分（0-100）'),
    sa.Column('overall_progress', sa.Integer(), nullable=False, comment='总体进度百分比（0-100）'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='completed | learning | behind'),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_stats_student_id'), 'student_stats', ['student_id'], unique=True)
    op.alter_column('badges', 'icon',
               existing_type=sa.VARCHAR(length=20),
               comment='Emoji 图标',
               existing_nullable=False,
               existing_server_default=sa.text("'🏅'::character varying"))
    op.alter_column('badges', 'condition_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="获取条件，如 {type: 'complete_unit', unit_id: 1}",
               existing_nullable=True)
    op.alter_column('blocks', 'block_type',
               existing_type=sa.VARCHAR(length=50),
               comment='对应前端 BlockType: description | reading_guide | task_driven | ...',
               existing_nullable=False)
    op.alter_column('blocks', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment='Block 标题（冗余字段，方便列表展示）',
               existing_nullable=True)
    op.alter_column('blocks', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='在主题内的渲染顺序',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('blocks', 'config_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='前端渲染所需的完整 JSON 配置',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('student_progress', 'current_block_order',
               existing_type=sa.INTEGER(),
               comment='当前步骤索引',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('student_responses', 'score',
               existing_type=sa.INTEGER(),
               comment='AI 打分（可选）',
               existing_nullable=True)
    op.alter_column('themes', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment='主题标题',
               existing_nullable=False)
    op.alter_column('themes', 'description',
               existing_type=sa.TEXT(),
               comment='主题描述',
               existing_nullable=True)
    op.alter_column('themes', 'theme_type',
               existing_type=sa.VARCHAR(length=50),
               comment='类型: themeReading | themeActivity | techniqueLearning',
               existing_comment='themeReading | themeActivity | techniqueLearning',
               existing_nullable=False)
    op.alter_column('themes', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='在单元内的排序',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('units', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='排序权重，越小越靠前',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('units', 'is_published',
               existing_type=sa.BOOLEAN(),
               comment='是否发布',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('units', 'is_published',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否发布',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('units', 'sort_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='排序权重，越小越靠前',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('themes', 'sort_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='在单元内的排序',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('themes', 'theme_type',
               existing_type=sa.VARCHAR(length=50),
               comment='themeReading | themeActivity | techniqueLearning',
               existing_comment='类型: themeReading | themeActivity | techniqueLearning',
               existing_nullable=False)
    op.alter_column('themes', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='主题描述',
               existing_nullable=True)
    op.alter_column('themes', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='主题标题',
               existing_nullable=False)
    op.alter_column('student_responses', 'score',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='AI 打分（可选）',
               existing_nullable=True)
    op.alter_column('student_progress', 'current_block_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='当前步骤索引',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('blocks', 'config_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='前端渲染所需的完整 JSON 配置',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('blocks', 'sort_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='在主题内的渲染顺序',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('blocks', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Block 标题（冗余字段，方便列表展示）',
               existing_nullable=True)
    op.alter_column('blocks', 'block_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='对应前端 BlockType: description | reading_guide | task_driven | ...',
               existing_nullable=False)
    op.alter_column('badges', 'condition_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment="获取条件，如 {type: 'complete_unit', unit_id: 1}",
               existing_nullable=True)
    op.alter_column('badges', 'icon',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Emoji 图标',
               existing_nullable=False,
               existing_server_default=sa.text("'🏅'::character varying"))
    op.drop_index(op.f('ix_student_stats_student_id'), table_name='student_stats')
    op.drop_table('student_stats')
    op.drop_table('users')
    # ### end Alembic commands ###
